
namespace OVR.API
{
  public enum MessageTypes
  {
    NONE = 0,
    INFO,
    APP_CONNECT,
    APP_DISCONNECT,
    DEVICE_CONNECTED,
    DEVICE_DISCONNECTED,
    DEVICE_STATE,
    DEVICE_STATE_REQUEST,
    DEVICE_CONFIG,
    DEVICE_CONFIG_REQUEST,
    DEVICE_VERSION,
    DEVICE_VERSION_REQUEST,
    DEVICE_BATTERY_LEVEL,
    DEVICE_BATTERY_LEVEL_REQUEST,
    DEVICE_HOSTNAME,
    DEVICE_HOSTNAME_REQUEST,
    DEVICE_FAN,
    DEVICE_DEBUGMODE,
    DEVICE_DEBUGMODE_REQUEST,
    ODORANT_COMMAND,
    ODORANT_COMMANDS
  }

  public enum DeviceState
  {
    NO_STATE = 0,
    CONFIG_STATE,
    SERIAL_STATE,
    WIFI_STATE
  };
}
